//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Calculator.CalcServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://websrv.cs.fsu.edu/~engelen/calc.wsdl", ConfigurationName="CalcServ.calcPortType")]
    public interface calcPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:calc) of message addRequest does not match the default value (http://websrv.cs.fsu.edu/~engelen/calc.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Calculator.CalcServ.addResponse add(Calculator.CalcServ.addRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Calculator.CalcServ.addResponse> addAsync(Calculator.CalcServ.addRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:calc) of message subRequest does not match the default value (http://websrv.cs.fsu.edu/~engelen/calc.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Calculator.CalcServ.subResponse sub(Calculator.CalcServ.subRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Calculator.CalcServ.subResponse> subAsync(Calculator.CalcServ.subRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:calc) of message mulRequest does not match the default value (http://websrv.cs.fsu.edu/~engelen/calc.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Calculator.CalcServ.mulResponse mul(Calculator.CalcServ.mulRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Calculator.CalcServ.mulResponse> mulAsync(Calculator.CalcServ.mulRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:calc) of message divRequest does not match the default value (http://websrv.cs.fsu.edu/~engelen/calc.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Calculator.CalcServ.divResponse div(Calculator.CalcServ.divRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Calculator.CalcServ.divResponse> divAsync(Calculator.CalcServ.divRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:calc) of message powRequest does not match the default value (http://websrv.cs.fsu.edu/~engelen/calc.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Calculator.CalcServ.powResponse pow(Calculator.CalcServ.powRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Calculator.CalcServ.powResponse> powAsync(Calculator.CalcServ.powRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class addRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double b;
        
        public addRequest() {
        }
        
        public addRequest(double a, double b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double result;
        
        public addResponse() {
        }
        
        public addResponse(double result) {
            this.result = result;
        }

        public static implicit operator double(addResponse v)
        {
            throw new NotImplementedException();
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sub", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class subRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double b;
        
        public subRequest() {
        }
        
        public subRequest(double a, double b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subResponse", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class subResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double result;
        
        public subResponse() {
        }
        
        public subResponse(double result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mul", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class mulRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double b;
        
        public mulRequest() {
        }
        
        public mulRequest(double a, double b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mulResponse", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class mulResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double result;
        
        public mulResponse() {
        }
        
        public mulResponse(double result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="div", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class divRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double b;
        
        public divRequest() {
        }
        
        public divRequest(double a, double b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divResponse", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class divResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double result;
        
        public divResponse() {
        }
        
        public divResponse(double result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pow", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class powRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double b;
        
        public powRequest() {
        }
        
        public powRequest(double a, double b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="powResponse", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class powResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double result;
        
        public powResponse() {
        }
        
        public powResponse(double result) {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface calcPortTypeChannel : Calculator.CalcServ.calcPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class calcPortTypeClient : System.ServiceModel.ClientBase<Calculator.CalcServ.calcPortType>, Calculator.CalcServ.calcPortType {
        
        public calcPortTypeClient() {
        }
        
        public calcPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public calcPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calcPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calcPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Calculator.CalcServ.addResponse Calculator.CalcServ.calcPortType.add(Calculator.CalcServ.addRequest request) {
            return base.Channel.add(request);
        }
        
        public double add(double a, double b) {
            Calculator.CalcServ.addRequest inValue = new Calculator.CalcServ.addRequest();
            inValue.a = a;
            inValue.b = b;
            Calculator.CalcServ.addResponse retVal = ((Calculator.CalcServ.calcPortType)(this)).add(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Calculator.CalcServ.addResponse> Calculator.CalcServ.calcPortType.addAsync(Calculator.CalcServ.addRequest request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<Calculator.CalcServ.addResponse> addAsync(double a, double b) {
            Calculator.CalcServ.addRequest inValue = new Calculator.CalcServ.addRequest();
            inValue.a = a;
            inValue.b = b;
            return ((Calculator.CalcServ.calcPortType)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Calculator.CalcServ.subResponse Calculator.CalcServ.calcPortType.sub(Calculator.CalcServ.subRequest request) {
            return base.Channel.sub(request);
        }
        
        public double sub(double a, double b) {
            Calculator.CalcServ.subRequest inValue = new Calculator.CalcServ.subRequest();
            inValue.a = a;
            inValue.b = b;
            Calculator.CalcServ.subResponse retVal = ((Calculator.CalcServ.calcPortType)(this)).sub(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Calculator.CalcServ.subResponse> Calculator.CalcServ.calcPortType.subAsync(Calculator.CalcServ.subRequest request) {
            return base.Channel.subAsync(request);
        }
        
        public System.Threading.Tasks.Task<Calculator.CalcServ.subResponse> subAsync(double a, double b) {
            Calculator.CalcServ.subRequest inValue = new Calculator.CalcServ.subRequest();
            inValue.a = a;
            inValue.b = b;
            return ((Calculator.CalcServ.calcPortType)(this)).subAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Calculator.CalcServ.mulResponse Calculator.CalcServ.calcPortType.mul(Calculator.CalcServ.mulRequest request) {
            return base.Channel.mul(request);
        }
        
        public double mul(double a, double b) {
            Calculator.CalcServ.mulRequest inValue = new Calculator.CalcServ.mulRequest();
            inValue.a = a;
            inValue.b = b;
            Calculator.CalcServ.mulResponse retVal = ((Calculator.CalcServ.calcPortType)(this)).mul(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Calculator.CalcServ.mulResponse> Calculator.CalcServ.calcPortType.mulAsync(Calculator.CalcServ.mulRequest request) {
            return base.Channel.mulAsync(request);
        }
        
        public System.Threading.Tasks.Task<Calculator.CalcServ.mulResponse> mulAsync(double a, double b) {
            Calculator.CalcServ.mulRequest inValue = new Calculator.CalcServ.mulRequest();
            inValue.a = a;
            inValue.b = b;
            return ((Calculator.CalcServ.calcPortType)(this)).mulAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Calculator.CalcServ.divResponse Calculator.CalcServ.calcPortType.div(Calculator.CalcServ.divRequest request) {
            return base.Channel.div(request);
        }
        
        public double div(double a, double b) {
            Calculator.CalcServ.divRequest inValue = new Calculator.CalcServ.divRequest();
            inValue.a = a;
            inValue.b = b;
            Calculator.CalcServ.divResponse retVal = ((Calculator.CalcServ.calcPortType)(this)).div(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Calculator.CalcServ.divResponse> Calculator.CalcServ.calcPortType.divAsync(Calculator.CalcServ.divRequest request) {
            return base.Channel.divAsync(request);
        }
        
        public System.Threading.Tasks.Task<Calculator.CalcServ.divResponse> divAsync(double a, double b) {
            Calculator.CalcServ.divRequest inValue = new Calculator.CalcServ.divRequest();
            inValue.a = a;
            inValue.b = b;
            return ((Calculator.CalcServ.calcPortType)(this)).divAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Calculator.CalcServ.powResponse Calculator.CalcServ.calcPortType.pow(Calculator.CalcServ.powRequest request) {
            return base.Channel.pow(request);
        }
        
        public double pow(double a, double b) {
            Calculator.CalcServ.powRequest inValue = new Calculator.CalcServ.powRequest();
            inValue.a = a;
            inValue.b = b;
            Calculator.CalcServ.powResponse retVal = ((Calculator.CalcServ.calcPortType)(this)).pow(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Calculator.CalcServ.powResponse> Calculator.CalcServ.calcPortType.powAsync(Calculator.CalcServ.powRequest request) {
            return base.Channel.powAsync(request);
        }
        
        public System.Threading.Tasks.Task<Calculator.CalcServ.powResponse> powAsync(double a, double b) {
            Calculator.CalcServ.powRequest inValue = new Calculator.CalcServ.powRequest();
            inValue.a = a;
            inValue.b = b;
            return ((Calculator.CalcServ.calcPortType)(this)).powAsync(inValue);
        }
    }
}
